### ISSUE TITLE
lmr: time window for possible simulations is incorrect

### ISSUE THREAD

**Issue by maelysLeratRosso** [OpenRailAssociation/osrd#10838]
### What happened?

Now : one can start a simulation with a departure between J+1 17h and J+7 (anytime), no matter when the simulation is done.

### What did you expect to happen?

The expected behavior is : 
Before 17h, one can start a simulation between J+1 and J+7 (anytime for both)
After 17h, one can start a simulation between J+2 and J+7 (anytime for both)

### How can we reproduce it (as minimally and precisely as possible)?

-

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

8aaefd4

**Comment by bloussou** [comment]
# Meeting 18/02/2025 @flomonster @clarani @bloussou @elise-chin 

## Ideas
### handle this in `osrd-data`
#### pros
- Quick and dirty
#### cons
- Shady backend feature
- We have to decorrelate basic caching and stdcm search env change since we don't know basic caching duration (between 20min and 1h)
- probably too much logic in private code for a feature that should be public

### handle this in `editoast`
#### pros
- history of search envs
- no need to change `osrd-data` logic
- strong resilience to the switch `16h59 -> 17h`
- end of `stdcm search env` with 1 row table in editoast datamodel
#### cons
- more complexity

✅ We decided solution 2 is better.

## Refinement

### Editoast
```yml
id: 0
electrical_profile_set_id: 0
infra_id: 0
search_window_begin: "2025-02-18T00:00:00Z"
search_window_end: "2025-02-24T23:59:59Z"
temporary_speed_limit_group_id: 0
timetable_id: 0
work_schedule_group_id: 0
# New fields
enabled_from: "2025-02-17T17:00:00Z"
enabled_to: "2025-02-18T17:00:00Z"
```

Adapt `GET /search_env` and `POST /search_env`:
- GET: 
    - Take the env that is in the enabled env and if there are multiple just take the newer. 
    - If no env is enabled then take the most recent `enabled_to`
- POST: keep it stupid
    - Just check `enabled_from < enabled_to` 
    - in dev mod set `enabled_*` in the past and far future

Migration:
Set the dates of `enabled_*` in the past, if there is only 1 env this one will be picked with the fallback logic.

### osrd-data
Change the calls to `POST /stdcm_search_env` with the correct `enabled_*`
