### ISSUE TITLE
editoast: paced train: adapt endpoints for front

### ISSUE THREAD

**Issue by younesschrifi** [OpenRailAssociation/osrd#11451]
### Description and goal

Adding exceptions to paced trains: creating fake endpoints to allow front-end to work

### Acceptance criteria

- [x] Adapt paced train schema and add `struct Exceptions`  (see below)
- [x] Adapt get/put/post paced train endpoint
- [x] Adapt `paced_train/simulation_summary` endpoint #11856
- [ ] Adapt `paced_train/project_path` endpoint
- [x] Adapt `timetable/id/conflicts` endpoint #11859
- [x] Adapt `/paced_train/id/path` endpoint  **Add a query param: exception=id_of_exception** #11851
- [x] Adapt `paced_train/id/simulation` endpoint  **Add a query param: exception=id_of_exception** #11851

https://github.com/osrd-project/osrd-confidential/issues/980

**Comment by younesschrifi** [comment]
```
# Type of exception
id: eac43ba6-cfd9-4896-b7c9-987b9d26937b # UUID généré par le front, scoped par mission
disabled: false # only if not created
occurence_index: 3 # only if not created


# Modifications
train_name: # or null
  value: "ABC3615"

rolling_stock: # or null
  rolling_stock_name: R2D2
  comfort: AIR_CONDITIONING # or HEATING, default STANDARD

labels: # or null
  value: ["tchou-tchou", "choo-choo"]

category: # or null
 value: "fast_train"

speed_limit_tag: # or null
  value: "MA100"

start_time: # or null
  value: "2023-12-21T08:51:11.914897+00:00" # or null

constraint_distribution: # or null
  value: MARECO

path_and_schedule: # or null
  path:
  - {id: a, uic: 87210} # Any operational point matching the given uic
  - {id: b, track: foo, offset: 10000} # 10m on track foo
  - {id: c, deleted: true, trigram: ABC} # Any operational point matching the trigram ABC
  - {id: d, operational_point: X} # A specified operational point
  schedule:
  - {at: a, stop_for: PT5M, locked: true} # inferred arrival to be equal to start_time
  - {at: b, arrival: PT10M, stop_for: PT5M}
  - {at: c, stop_for: PT5M}
  - {at: d, arrival: PT50M, locked: true, reception_signal: SHORT_SLIP_STOP}
  margins:
    boundaries: [b, c]
    values: ["5%", "3%", "4.5min/100km"]
  power_restrictions:
  - {from: b, to: c, value: "M1C1"}

initial_speed: # or null
  value: 2.5

options: # or null
  value:
    use_electrical_profiles: true
    use_speed_limits_for_simulation: false
```
