### ISSUE TITLE
editoast: add exceptions field to paced train model

### ISSUE THREAD

**Issue by younesschrifi** [OpenRailAssociation/osrd#11453]
Write the migration to add exceptions to Paced Train

part of https://github.com/osrd-project/osrd-confidential/issues/980

```yml
# Type of exception
id: eac43ba6-cfd9-4896-b7c9-987b9d26937b # UUID généré par le front, scoped par mission
disabled: false # only if not created
occurence_index: 3 # only if not created


# Modifications
train_name: # or null
  value: "ABC3615"

rolling_stock: # or null
  rolling_stock_name: R2D2
  comfort: AIR_CONDITIONING # or HEATING, default STANDARD

labels: # or null
  value: ["tchou-tchou", "choo-choo"]

category: # or null
 value: "fast_train"

speed_limit_tag: # or null
  value: "MA100"

start_time: # or null
  value: "2023-12-21T08:51:11.914897+00:00" # or null

constraint_distribution: # or null
  value: MARECO

path_and_schedule: # or null
  path:
  - {id: a, uic: 87210} # Any operational point matching the given uic
  - {id: b, track: foo, offset: 10000} # 10m on track foo
  - {id: c, deleted: true, trigram: ABC} # Any operational point matching the trigram ABC
  - {id: d, operational_point: X} # A specified operational point
  schedule:
  - {at: a, stop_for: PT5M, locked: true} # inferred arrival to be equal to start_time
  - {at: b, arrival: PT10M, stop_for: PT5M}
  - {at: c, stop_for: PT5M}
  - {at: d, arrival: PT50M, locked: true, reception_signal: SHORT_SLIP_STOP}
  margins:
    boundaries: [b, c]
    values: ["5%", "3%", "4.5min/100km"]
  power_restrictions:
  - {from: b, to: c, value: "M1C1"}

initial_speed: # or null
  value: 2.5

options: # or null
  value:
    use_electrical_profiles: true
    use_speed_limits_for_simulation: false
```

// Can be serde(untagged)
```
enum ExceptionType {
  Modified{occurence_index: int, disabled: bool},
  Created,
}
```

Exemple de réponse de l'endpoint /paced_train/simulation_summary

```json
{
  "train_42": {
    "paced_train": {
      "energy_consumption": 0,
      "length": 0,
      "path_item_times_base": [
        0
      ],
      "path_item_times_final": [
        0
      ],
      "path_item_times_provisional": [
        0
      ],
      "status": "success",
      "time": 0
    },
    "exceptions": {
      "42432-234234-243242-23434": {
        "energy_consumption": 0,
        "length": 0,
        "path_item_times_base": [
          0
        ],
        "path_item_times_final": [
          0
        ],
        "path_item_times_provisional": [
          0
        ],
        "status": "success",
        "time": 0
      }
    }
  }
}
```
