### ISSUE TITLE
editoast: create `project_path_op` endpoint for train schedule

### ISSUE THREAD

**Issue by Yohh** [OpenRailAssociation/osrd#11536]
- [x] create `project_path` endpoint in `views/timetable/train_schedule`
- [x] input:
```yaml
infra_id: 0
electrical_profile_set_id: 0
ids: [ 42, 24 ]
operational_points: # contains the list of op (size N)
  - id_op_1
  - id_op_2
operational_points_distances: # contains distances between each op (size N - 1)
  - 420000 # 420m (in mm)
```
- [x] output:
```yaml
42: # train id
  # First curve
  - positions:  [ 0, 400000 ] # In mm
    times: [ 0, 90 ] # In s
  # Second curve (can be a point if only one item)
  - positions:  [ 420000 ] # In mm
    times: [ 120 ] # In s
  departure_time: "2025-04-07T13:51:46.053Z"
  rolling_stock_length: 0 # Should we keep it ? (Currently not used in project_path)
```
