### ISSUE TITLE
Wrong behavior with scenario patch endpoint

### ISSUE THREAD

**Issue by flomonster** [OpenRailAssociation/osrd#3784]
Editoast openapi describes the scenario patch payload as follows:

```yaml
    ScenarioRequest:
      properties:
        name:
          type: string
          maxLength: 128
        description:
          type: string
          maxLength: 1024
        tags:
          type: array
          items:
            type: string
            maxLength: 255
        infra:
          type: integer
        electrical_profile_set:
          type: number
          nullable: true
          description: Electrical profile set id (if any)
      required:
        - "name"
```

Adapt the openapi:

- Name shouldn't be required
- `electrical_profile_set` shouldn't be modifiable

Adapt the implementation:

- Remove `electrical_profile_set` from the `ScenarioPatchForm`.
- Using `Option` of `Option` is useless when deserializing.
