### ISSUE TITLE
TS2: Add editoast project path endpoint

### ISSUE THREAD

**Issue by flomonster** [OpenRailAssociation/osrd#6858]
## Description

Implementation of the `POST` `/v2/train_schedule/project_path?infra=N&ids[]=X&ids[]=Y`.

The response should contain all the information needed to display the time-space chart.

- Time-Space points
- Blocks with their colors (using the core signal projection endpoint)

## AC

- [ ] The signal projection call can be mocked for now (see [#6856](https://github.com/osrd-project/osrd/issues/6856))
- [ ] Each train projection should be cached
- [ ] The signal projection query should be cached
- [ ] A `404` should be returned if the infra is not found
- [ ] A `404` should be returned if a train id is not found

#### Body input of the editoast endpoint

```yaml
routes: Vec<Identifier> # Might not be needed
track_section_ranges: Vec<TrackRange>
```

#### Output of the editoast endpoint

```yaml
# Space-Time chart information
42: # Train id (requested)
  departure_time: 2024-04-11T15:26:37+00:00
  space_time_curves: # List of space-time curve sections
    - times: Vec<u64> # List of times in seconds/milliseconds since `departure_time`.
      positions: Vec<u64> # List of positions in mm
  rolling_stock_length: u64 # Useful to compute the tail positions curve

  blocks_aspects:
    - signal_id: signal_42
      time_start: i64 # Times since `departure_time` in seconds. (Can be negative)
      time_end: i64 # Times since `departure_time` in seconds. (Can be negative)
      position_start: u64 # Position on path in mm
      position_end: u64 # Position on the path in mm
      # The color of the aspect
      # (Bits 24-31 are alpha, 16-23 are red, 8-15 are green, 0-7 are blue)
      color: i32
      blinking: false
      aspect_label: CARRE

  speeds: f64 # Wait for the GET design, might be needed
```

### Workflow

```mermaid
flowchart TB
    Input[Input]
    TC[Trains to compute]
    TI[Train input]
    BA[Blocks aspects]
    HP[Space-Time Curves]
    PT[Projected train]
    Output[Projected trains]

    Input -->|Split / Compute input| TI
    TI -->|Hit Cache| PT
    TI -->|Miss Cache\nAggregate| TC
    TC -->|"Path projection (editoast)"| HP
    TC -->|"Signal projection (core)"| BA
    HP --> PT
    BA --> PT
    PT -->|Merge| Output
```

-----------------------

> [!NOTE]
> We should provide the time and the length of the path to the core endpoint `/v2/project_signals`.
> This way we don't have optional values for `time_end` and `position_end`
