### ISSUE TITLE
Add whitelist to the gateway

### ISSUE THREAD

**Issue by flomonster** [OpenRailAssociation/osrd#7229]
## Description

Add a whitelist option to the gateway config file.

```toml
[[auth.providers]]
type = "Oidc"
provider_id = "example_provider"
issuer_url = "https://%PROVIDER_URL%"
post_login_url = "https://%POST_LOGIN_URL%"
callback_url = "https://%APP_ROOT_URL%/auth/provider/example_provider/callback"
client_id = "%CLIENT_ID%"
client_secret = "%CLIENT_SECRET%"
username_whitelist = ["user_1", "user_2"] # <--- Optional field
```

## AC

- The `username_whitelist` config should be optional (if not provided no filter should be applied)
- The whitelist only makes sense for the OIDC provider
- The gateway should return a `403` when a user is not on the white list
