### ISSUE TITLE
Implement editoast endpoint for work schedules projection

### ISSUE THREAD

**Issue by anisometropie** [OpenRailAssociation/osrd#8642]
# Decription

```yaml
- type: CATENARY
  start_date_time: "2023-12-21T08:51:00+00:00"
  end_date_time: "2023-12-21T10:30:00+00:00"
  # MUST NOT be empty
  path_position_ranges:
    # Ranges in mm
    - [20_000, 100_000]
    - [150_000, 300_000]
- type: TRACK
  start_date_time: "2023-12-21T08:51:00+00:00"
  end_date_time: "2023-12-21T10:30:00+00:00"
  path_position_ranges:
    - [20_000, 100_000]
    - [150_000, 300_000]
```

### Endpoint

Create a new [endpoint](https://github.com/osrd-project/osrd-confidential/issues/531#issuecomment-2258547362)
