### ISSUE TITLE
core, editoast: add requirements field to conflict list

### ISSUE THREAD

**Issue by emersion** [OpenRailAssociation/osrd#8680]
### Description and goal

Return a new requirements field in the conflict list:

```yaml
- conflict_type: Spacing
  train_ids: [0, 1]
  start_time: "2024-08-07T08:50:17.421Z"
  duration: 120_000 # ms
  requirements:
    - time_range: [0, 50_000]
      # Core uses routing_requirements and spacing_requirements to deduce zones
      zones: ["zone_1", "zone_2"]
    - time_range: [45_000, 120_000]
      zones: ["zone_3"]
```

### Acceptance criteria

.
