### ISSUE TITLE
core, editoast: add new project_conflicts endpoint

### ISSUE THREAD

**Issue by emersion** [OpenRailAssociation/osrd#8682]
### Description and goal

Add a new endpoint to project a list of conflicts along a path.

```yaml
- conflict_type: Spacing
  train_ids: [0, 1]
  start_time: "2024-08-07T08:50:17.421Z"
  duration: 120_000 # ms
  requirements:
    - time_range: [0, 50_000]
      space_range: [420_000, 500_000] # Manchette offset in mm
    - time_range: [45_000, 120_000]
      space_range: [485_000, 580_000]
```

### Acceptance criteria

.
